spring.application.name=test_parnas
server.port=8099

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5457/orders_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:orders_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:orders_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:orders_user}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:orders_password}
